config_file: /home/vmsoft/anylabeling_data/models/mobile_sam_20230629/config.yaml
decoder_model_path: sam_vit_h_4b8939.decoder.onnx
display_name: Segment Anything (MobileSAM)
encoder_model_path: mobile_sam.encoder.onnx
has_downloaded: true
input_size: 1024
max_height: 682
max_width: 1024
name: mobile_sam_20230629
type: segment_anything
